#! /bin/sh
### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $local_fs $remote_fs $network $nginx
# Required-Stop:     $local_fs $remote_fs $network $nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn web server
### END INIT INFO
#
# Install with: update-rc.d unicorn defaults 99

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=echojs
HOME=/home/echojs
ENV=production
PID=`cat $HOME/echojs/tmp/pids/unicorn.pid`

as_user() {
	if [ "xroot" != "x`whoami`" ]
	then
		bash -c "$2"
	else
		su - -c "$2" $1
	fi
}

case "$1" in
	start)
		echo "Starting unicorn for user '$USER'"
		as_user $USER "cd $HOME/echojs; unicorn -c config/unicorn.rb -E $ENV -D"
		echo "."
		;;

	stop)
		echo "Stopping unicorn for user '$USER'"
		kill -QUIT $PID
		echo "."
		;;

	restart)
		echo "Restarting unicorn for user '$USER'"
		kill -USR2 $PID
		sleep 1
		kill -QUIT $PID
		echo "."
		;;

	reload)
		echo "Reloading unicorn configuration for user '$USER'"
		kill -HUP $PID
		echo "."
		;;

	*)
		echo "Usage: /etc/init.d/unicorn {start|stop|reload|restart}"
		exit 1
esac

exit 0
